version: "3.9"
services:
    postgres:
        image: "postgres:latest"
        restart: always
        environment:
            - POSTGRES_USER=postgres
            - POSTGRES_PASSWORD=postgres
            - POSTGRES_DB=postgres
    flaskapp:
        build: .
        volumes:
            - .:/files
        ports:
            - "5000:5000"
        environment:
            FLASK_ENV: development
        depends_on:
            - postgres